lbKey:
  public: 0822f83228750e27d4264972fa87e9a4
  secret: 33b369d011d695540cd8b424c9aa4ea62c04ddce7800eb952ebeb822a20ec0cc

debug: true
#dumpQueries: true

qorAddress: ":8777"

proxy: ""
sentryDNS: ""

lbCheckTick: 30s

ratesRefreshTick: 10m
prefetchRates:
    - RUB
    - USD

db:
  debug:    true
  user:     postgres
  password: 1234
  host:     db
  port:     5432
  base:     postgres

rabbit:
  URL: "amqp://guest:guest@rabbit"
